name: Deploy                    # Name of the workflow

on:
  push:
    branches: ['main']         # Triggers when you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest     # Uses Ubuntu to run the deployment

    steps:
      - uses: actions/checkout@v4         # Gets your code from GitHub
      - uses: actions/setup-node@v3       # Sets up Node.js
        with:
          node-version: 18                # Uses Node.js version 18
      - run: npm ci                       # Installs dependencies
      - run: npm run build               # Builds your project
      - uses: peaceiris/actions-gh-pages@v3    # Deploys to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # Uses GitHub's automatic token
          publish_dir: ./dist            # Publishes the dist folder Vite creates